# The backend specifies how to connect to your Git repository.
backend:
  name: git-gateway
  branch: main # Or master, depending on your default branch name

# The media_folder is where images uploaded in the CMS will be stored.
media_folder: "assets/images" # Example path, adjust to your project
public_folder: "/assets/images" # How to access the media folder from the site root

# The collections define the content types your client can edit.
collections:
  - name: "pages" # A collection of single pages
    label: "Pages"
    files:
      - file: "index.html" # The path to the file to be edited
        label: "Home Page"
        name: "home"
        fields: # The list of editable fields in this file
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}